### ISSUE TITLE
Would be nice to update it only if it is newer

### ISSUE THREAD

**Issue by emartynov** [garrefa/automation-scripts#1]
Line:
https://github.com/garrefa/automation-scripts/blob/d83e4689c0ae20c94a7e6fd428ec2b3bcf68506e/install-gitlab-runner.sh#L41

This script will replace gitlab runner whenever you already have newest.

Would be nice to do it only if it is really required.

**Comment by garrefa** [comment]
True, but above this it checks if gitlab-runner is already installed.
In case its installed the script will tell you that it's already installed and ask if you want to update and in case you don't say yes the script will terminate.
Do you think this check/question is ok or you still think would be good to check versions?

```
# Check if gitlab-runner is already installed and if it is ask the user if he wants to update
which gitlab-runner >> /dev/null
if [ $(echo $?) == 0 ]; then
    UPDATE=true
    read -p "Gitlab runner is already installed, do you want to update it? [y/N] " answer
    if [ $answer != "y" ]; then
        exit 0
    fi
```

**Comment by emartynov** [comment]
Oke, I should re-phrase my original message: 

It would be nice to aks user to update only if an update exists.

But up to you. Please feel free to close the ticket if it is important or relevant.

**Comment by garrefa** [comment]
Closing since we talked in person
